"""Financial research lenses for capital-intensive clean energy companies."""

from __future__ import annotations

from .models import Dimension


def _f(
    id_: str,
    name: str,
    objective: str,
    cues: tuple[str, ...],
    terms: tuple[str, ...],
    questions: tuple[str, ...],
) -> Dimension:
    return Dimension(id_, "Financial & Bankability", name, objective, cues, terms, questions)


FINANCE_DIMENSIONS: tuple[Dimension, ...] = (
    _f(
        "revenue-traction-quality",
        "Revenue, Traction & Quality",
        "Find evidence behind revenue growth: binding orders, revenue recognition, backlog conversion, repeat customers, and concentration.",
        (
            "revenue recognition",
            "remaining performance obligations",
            "customer concentration",
            "purchase order",
            "commercial contract",
            "repeat customer",
            "backlog conversion",
            "收入确认",
            "客户集中度",
            "在手订单转化",
            "商业合同",
        ),
        (
            "revenue",
            "sales",
            "backlog",
            "customer",
            "contract",
            "order",
            "收入",
            "订单",
            "客户",
        ),
        (
            "How much demand is binding, funded, cancellable, or conditional?",
            "What share of revenue depends on one customer, project, or subsidy?",
        ),
    ),
    _f(
        "profitability-unit-economics",
        "Profitability & Unit Economics",
        "Find evidence for gross margin, delivered cost, warranty burden, pricing power, and the scale assumptions required for profitability.",
        (
            "gross margin",
            "operating revenue",
            "operating costs",
            "cost of revenue",
            "unit economics",
            "warranty reserve",
            "cost reduction roadmap",
            "average selling price",
            "毛利率",
            "营业成本",
            "单位经济性",
            "质保准备",
            "降本路径",
        ),
        (
            "margin",
            "profit",
            "cost",
            "price",
            "warranty",
            "scale",
            "毛利",
            "盈利",
            "成本",
        ),
        (
            "Are current margins measured or projected at a future production scale?",
            "Which cost reductions depend on yield, utilization, or commodity assumptions?",
        ),
    ),
    _f(
        "cash-runway",
        "Cash Flow & Runway",
        "Find evidence on operating cash burn, free cash flow, unrestricted liquidity, working capital, and the date of the next funding need.",
        (
            "net cash flow from operating activities",
            "net cash flows from operating activities",
            "cash and cash equivalents at the end of the period",
            "cash payments to acquire fixed",
            "free cash flow",
            "cash runway",
            "unrestricted cash",
            "working capital deficit",
            "经营活动现金流",
            "自由现金流",
            "现金跑道",
            "期末现金及现金等价物",
        ),
        (
            "cash",
            "liquidity",
            "burn",
            "working capital",
            "operating activities",
            "现金流",
            "流动性",
            "营运资金",
        ),
        (
            "How many months of runway remain at the latest observed burn rate?",
            "Which milestones must be reached before the next financing?",
        ),
    ),
    _f(
        "capex-scale-up",
        "Capital Intensity & Scale-up",
        "Find evidence on capital expenditure, factory and project build-out, capacity utilization, yield, and remaining capital required to scale.",
        (
            "capital expenditures",
            "property plant and equipment",
            "manufacturing capacity",
            "capacity utilization",
            "production yield",
            "factory expansion",
            "资本开支",
            "固定资产",
            "产能利用率",
            "生产良率",
            "工厂扩建",
        ),
        (
            "capex",
            "capital expenditure",
            "factory",
            "capacity",
            "production",
            "yield",
            "资本开支",
            "产能",
            "生产",
        ),
        (
            "How much additional capital is required before positive free cash flow?",
            "Does installed capacity translate into qualified, saleable output?",
        ),
    ),
    _f(
        "balance-sheet-funding",
        "Balance Sheet & Funding Dependency",
        "Find evidence on debt, covenants, dilution, government support, off-balance-sheet commitments, and financing conditions.",
        (
            "convertible notes",
            "debt covenant",
            "at-the-market offering",
            "share dilution",
            "government grant",
            "financing condition",
            "可转换债券",
            "债务契约",
            "股权稀释",
            "政府补助",
            "融资条件",
        ),
        (
            "debt",
            "financing",
            "equity",
            "dilution",
            "grant",
            "commitment",
            "债务",
            "融资",
            "稀释",
            "补助",
        ),
        (
            "Which funding sources are committed versus merely available or expected?",
            "What covenants, dilution, or policy conditions could restrict capital access?",
        ),
    ),
    _f(
        "project-bankability",
        "Project Bankability",
        "Find evidence that lenders, insurers, developers, and customers can underwrite projects using the technology.",
        (
            "project finance",
            "non-recourse financing",
            "performance guarantee",
            "bankable warranty",
            "insurance coverage",
            "lender technical advisor",
            "project internal rate of return",
            "项目融资",
            "无追索权融资",
            "性能保证",
            "保险覆盖",
            "项目内部收益率",
        ),
        (
            "bankability",
            "lender",
            "insurance",
            "guarantee",
            "warranty",
            "project finance",
            "可融资性",
            "贷款人",
            "保险",
            "担保",
        ),
        (
            "Has an independent lender or insurer accepted the technology risk?",
            "Are warranties, degradation assumptions, and remedies financeable at project tenor?",
        ),
    ),
)


FINANCE_BY_ID = {dimension.id: dimension for dimension in FINANCE_DIMENSIONS}
