"""A compact, original implementation of the DOE ARL dimension structure.

Dimension names follow the U.S. Department of Energy ARL framework. Objectives,
retrieval cues, and review questions are original project content and are not a
copy of the DOE assessment instrument.
"""

from __future__ import annotations

from .models import Dimension


def _d(
    id_: str,
    category: str,
    name: str,
    objective: str,
    cues: tuple[str, ...],
    query_terms: tuple[str, ...],
    questions: tuple[str, ...],
) -> Dimension:
    return Dimension(id_, category, name, objective, cues, query_terms, questions)


DIMENSIONS: tuple[Dimension, ...] = (
    _d(
        "delivered-cost",
        "Value Proposition",
        "Delivered Cost",
        "Find evidence about the customer's total cost to acquire, install, operate, and retire the solution.",
        (
            "levelized cost",
            "total cost of ownership",
            "installed cost",
            "cost per kwh",
            "cost per kw",
            "operating cost",
            "system cost",
            "平准化成本",
            "全生命周期成本",
        ),
        (
            "cost",
            "price",
            "economics",
            "margin",
            "installation",
            "maintenance",
            "decommissioning",
            "成本",
            "价格",
            "经济性",
        ),
        (
            "Is delivered cost compared on the same boundary and duty cycle as alternatives?",
            "Which cost assumptions remain unverified at commercial scale?",
        ),
    ),
    _d(
        "functional-performance",
        "Value Proposition",
        "Functional Performance",
        "Find measured performance against the requirements and incumbent alternatives that matter to buyers.",
        (
            "round-trip efficiency",
            "cycle life",
            "capacity factor",
            "performance guarantee",
            "field test",
            "demonstrated performance",
            "往返效率",
            "循环寿命",
            "性能保证",
            "示范运行",
        ),
        (
            "performance",
            "efficiency",
            "durability",
            "reliability",
            "availability",
            "test",
            "validation",
            "性能",
            "效率",
            "可靠性",
        ),
        (
            "Do results come from an independent test or only a company claim?",
            "Were operating conditions representative of the target use case?",
        ),
    ),
    _d(
        "ease-of-use",
        "Value Proposition",
        "Ease of Use / Complexity",
        "Find evidence about integration burden, operating complexity, switching costs, and required behavior change.",
        (
            "plug and play",
            "system integration",
            "installation time",
            "operator training",
            "retrofit",
            "interoperability",
            "系统集成",
            "安装周期",
            "运维培训",
            "兼容性",
        ),
        (
            "integration",
            "install",
            "operate",
            "complexity",
            "training",
            "workflow",
            "集成",
            "安装",
            "运维",
        ),
        (
            "What must the buyer, installer, or operator do differently?",
            "Are integration time and skills supported by deployments?",
        ),
    ),
    _d(
        "demand-maturity",
        "Market Acceptance",
        "Demand Maturity / Market Openness",
        "Find evidence of budgeted customer demand, procurement behavior, repeat orders, and willingness to adopt a new solution.",
        (
            "purchase order",
            "commercial contract",
            "repeat order",
            "customer pipeline",
            "backlog",
            "offtake agreement",
            "采购订单",
            "商业合同",
            "在手订单",
            "客户管线",
        ),
        (
            "customer",
            "demand",
            "contract",
            "order",
            "backlog",
            "procurement",
            "客户",
            "需求",
            "合同",
            "订单",
        ),
        (
            "Which demand signals are binding, funded, and near term?",
            "Does evidence show repeatable procurement rather than one-off pilots?",
        ),
    ),
    _d(
        "market-size",
        "Market Acceptance",
        "Market Size",
        "Find transparent estimates of the addressable market tied to a defined customer, geography, and use case.",
        (
            "total addressable market",
            "serviceable addressable market",
            "market size",
            "market forecast",
            "annual installations",
            "可服务市场",
            "市场规模",
            "市场预测",
        ),
        (
            "market",
            "segment",
            "forecast",
            "growth",
            "capacity",
            "addressable",
            "市场",
            "规模",
            "增长",
        ),
        (
            "Are market boundaries and assumptions explicit and reproducible?",
            "How much of the cited market is economically reachable by this product?",
        ),
    ),
    _d(
        "downstream-value-chain",
        "Market Acceptance",
        "Downstream Value Chain",
        "Find evidence that channels, integrators, service providers, buyers, and end-of-life actors can deliver the offering.",
        (
            "channel partner",
            "system integrator",
            "engineering procurement and construction",
            "distribution agreement",
            "service network",
            "recycling partner",
            "渠道伙伴",
            "系统集成商",
            "服务网络",
            "回收伙伴",
        ),
        (
            "channel",
            "integrator",
            "distributor",
            "service",
            "buyer",
            "recycling",
            "渠道",
            "集成商",
            "服务",
        ),
        (
            "Which downstream roles are contracted versus assumed?",
            "Where could a missing channel or service capability block adoption?",
        ),
    ),
    _d(
        "capital-flow",
        "Resource Maturity",
        "Capital Flow",
        "Find evidence that corporate, project, and customer capital can fund scale-up and deployment on workable terms.",
        (
            "project finance",
            "debt facility",
            "financing commitment",
            "tax equity",
            "bankability",
            "going concern",
            "项目融资",
            "授信额度",
            "融资承诺",
            "可融资性",
        ),
        (
            "capital",
            "finance",
            "funding",
            "cash",
            "debt",
            "investment",
            "资本",
            "融资",
            "现金",
        ),
        (
            "Is enough capital committed for the next commercialization milestone?",
            "Can customers finance projects using the technology without exceptional support?",
        ),
    ),
    _d(
        "project-delivery",
        "Resource Maturity",
        "Project Development / Integration / Management",
        "Find evidence of repeatable project origination, engineering, delivery, commissioning, and schedule control.",
        (
            "notice to proceed",
            "commissioned project",
            "commercial operation date",
            "engineering procurement construction",
            "project delay",
            "liquidated damages",
            "开工通知",
            "项目投运",
            "商业运行",
            "项目延期",
        ),
        (
            "project",
            "delivery",
            "commissioning",
            "schedule",
            "construction",
            "integration",
            "项目",
            "交付",
            "并网",
        ),
        (
            "Are schedule and cost outcomes available from multiple projects?",
            "Which delivery capabilities still depend on heroic or one-off effort?",
        ),
    ),
    _d(
        "infrastructure",
        "Resource Maturity",
        "Infrastructure",
        "Find evidence that required grid, transport, fueling, storage, communications, and site infrastructure exists or is funded.",
        (
            "grid interconnection",
            "transmission capacity",
            "charging infrastructure",
            "pipeline infrastructure",
            "port infrastructure",
            "interconnection queue",
            "电网接入",
            "输电容量",
            "充电基础设施",
            "并网队列",
        ),
        (
            "infrastructure",
            "grid",
            "interconnection",
            "transmission",
            "transport",
            "site",
            "基础设施",
            "并网",
            "输电",
        ),
        (
            "Which external infrastructure is on the critical path?",
            "Is that infrastructure available at target deployment sites and dates?",
        ),
    ),
    _d(
        "manufacturing-supply-chain",
        "Resource Maturity",
        "Manufacturing & Supply Chain",
        "Find evidence of qualified suppliers, production yield, capacity, quality systems, lead times, and scale-up plans.",
        (
            "manufacturing capacity",
            "production line",
            "qualified supplier",
            "production yield",
            "supply agreement",
            "quality management system",
            "制造产能",
            "生产线",
            "合格供应商",
            "良率",
            "供应协议",
        ),
        (
            "manufacturing",
            "production",
            "supplier",
            "capacity",
            "yield",
            "quality",
            "制造",
            "生产",
            "供应商",
            "产能",
        ),
        (
            "Is claimed capacity demonstrated, installed, financed, or only planned?",
            "Which quality and yield data are independently auditable?",
        ),
    ),
    _d(
        "materials-sourcing",
        "Resource Maturity",
        "Materials Sourcing",
        "Find evidence about critical inputs, geographic concentration, substitutes, contracting, traceability, and price exposure.",
        (
            "critical mineral",
            "raw material",
            "sole source",
            "long-term supply agreement",
            "commodity price",
            "material traceability",
            "关键矿产",
            "原材料",
            "单一来源",
            "长期供应协议",
            "大宗价格",
        ),
        (
            "material",
            "mineral",
            "commodity",
            "sourcing",
            "supply",
            "input",
            "材料",
            "矿产",
            "采购",
            "供应",
        ),
        (
            "Which inputs create concentration, volatility, or traceability risk?",
            "Are supply contracts sufficient for the intended ramp?",
        ),
    ),
    _d(
        "workforce",
        "Resource Maturity",
        "Workforce",
        "Find evidence that the required engineering, construction, manufacturing, sales, and operations skills can be hired and retained.",
        (
            "skilled workforce",
            "labor shortage",
            "workforce development",
            "training program",
            "collective bargaining",
            "employee retention",
            "技能人才",
            "劳动力短缺",
            "人才培训",
            "员工留任",
        ),
        (
            "workforce",
            "labor",
            "employee",
            "training",
            "talent",
            "hire",
            "人才",
            "劳动力",
            "招聘",
            "培训",
        ),
        (
            "Which skills are scarce at the planned deployment locations?",
            "Is the hiring and training plan backed by delivery experience?",
        ),
    ),
    _d(
        "regulatory-environment",
        "License to Operate",
        "Regulatory Environment",
        "Find evidence about mandatory rules, approvals, standards, certifications, and regulator treatment of the technology.",
        (
            "regulatory approval",
            "product certification",
            "safety standard",
            "code compliance",
            "interconnection standard",
            "certified to",
            "监管批准",
            "产品认证",
            "安全标准",
            "合规认证",
        ),
        (
            "regulation",
            "regulatory",
            "certification",
            "standard",
            "compliance",
            "approval",
            "监管",
            "认证",
            "标准",
            "合规",
        ),
        (
            "Which approvals are complete for the exact product and jurisdiction?",
            "Which standards or rules remain unsettled or subject to interpretation?",
        ),
    ),
    _d(
        "policy-environment",
        "License to Operate",
        "Policy Environment",
        "Find evidence about incentives, tariffs, public procurement, mandates, and exposure to policy change.",
        (
            "investment tax credit",
            "production tax credit",
            "government incentive",
            "domestic content",
            "trade tariff",
            "policy uncertainty",
            "投资税收抵免",
            "生产税收抵免",
            "政府补贴",
            "本地化要求",
            "关税",
        ),
        (
            "policy",
            "incentive",
            "subsidy",
            "tax credit",
            "tariff",
            "mandate",
            "政策",
            "补贴",
            "税收抵免",
            "关税",
        ),
        (
            "Would the value proposition survive a plausible policy change?",
            "Are eligibility and timing of incentives confirmed for target projects?",
        ),
    ),
    _d(
        "permitting-siting",
        "License to Operate",
        "Permitting & Siting",
        "Find evidence about site control, land use, environmental review, local permits, timelines, and opposition.",
        (
            "site control",
            "environmental impact statement",
            "environmental review",
            "permit application",
            "zoning approval",
            "permitting delay",
            "场地控制",
            "环境影响评价",
            "许可申请",
            "规划审批",
            "审批延期",
        ),
        (
            "permit",
            "siting",
            "zoning",
            "land",
            "environmental review",
            "location",
            "许可",
            "选址",
            "环评",
            "土地",
        ),
        (
            "What is the demonstrated permitting timeline in target jurisdictions?",
            "Are site control and local approvals secured for announced projects?",
        ),
    ),
    _d(
        "environmental-safety",
        "License to Operate",
        "Environmental & Safety",
        "Find evidence about lifecycle impacts, hazards, incidents, safety validation, waste, and end-of-life obligations.",
        (
            "life cycle assessment",
            "safety incident",
            "thermal runaway",
            "hazard analysis",
            "environmental footprint",
            "end of life",
            "生命周期评价",
            "安全事故",
            "热失控",
            "危害分析",
            "环境足迹",
        ),
        (
            "safety",
            "environmental",
            "hazard",
            "incident",
            "waste",
            "recycle",
            "安全",
            "环境",
            "事故",
            "回收",
        ),
        (
            "Are impacts assessed across the lifecycle and at commercial scale?",
            "What incident, testing, and mitigation evidence is independently available?",
        ),
    ),
    _d(
        "community-perception",
        "License to Operate",
        "Community Perception",
        "Find evidence about local benefits, stakeholder engagement, trust, opposition, equity, and grievance handling.",
        (
            "community engagement",
            "community benefit agreement",
            "public opposition",
            "stakeholder consultation",
            "environmental justice",
            "social license",
            "社区参与",
            "社区利益协议",
            "公众反对",
            "利益相关方沟通",
            "环境正义",
        ),
        (
            "community",
            "stakeholder",
            "public",
            "opposition",
            "equity",
            "benefit",
            "社区",
            "公众",
            "利益相关方",
            "反对",
        ),
        (
            "Whose acceptance is required and how has it been measured?",
            "Are local benefits and grievance mechanisms specific and enforceable?",
        ),
    ),
)


DIMENSION_BY_ID = {dimension.id: dimension for dimension in DIMENSIONS}


def framework_as_dicts() -> list[dict[str, object]]:
    """Return the framework in a JSON-friendly form."""
    return [
        {
            "id": d.id,
            "category": d.category,
            "name": d.name,
            "objective": d.objective,
            "review_questions": list(d.review_questions),
        }
        for d in DIMENSIONS
    ]
